name: Summeralities
description: "It’s always summer here.<br /><br />Art, writing, and increasing disquiet by Harris Lapiroff."
markdown: kramdown
highlighter: pygments
url: http://summer.whimsicaliti.es
safe: true
lsi: false
